version: '3'

networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/log/nginx/:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build: ./backend
    networks:
      - dev
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    networks:
      - dev
